# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9e0b3513dede22dc09523bc868c80f9914f9cda888672b2eb030559949ef07c1bca8c81289366a62d5464a0d8da8e92d2f5f2e059b6dfe3050468555f1e0604

test:
  secret_key_base: 468effff23ab05a6016a2306a1b1e4ecddaafb3d8100bedc0072188322df3cfae10ed2b689652b166f219594aa42b8027b60daba1a3ae16b5dea0bd32adb55ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
